return {
	"MeanderingProgrammer/render-markdown.nvim",
	dependencies = { "nvim-treesitter/nvim-treesitter", "nvim-mini/mini.nvim" }, -- if you use the mini.nvim suite
	completions = { lsp = { enabled = true } },
	opts = {
		heading = {
			enabled = true,
			render_modes = false,
			atx = true,
			setext = true,
			sign = true,
			icons = { "󰲡 ", "󰲣 ", "󰲥 ", "󰲧 ", "󰲩 ", "󰲫 " },
			position = "overlay",
			signs = { "󰫎 " },
			width = "full",
			left_margin = 0,
			left_pad = 0,
			right_pad = 0,
			min_width = 0,
			border = false,
			border_virtual = false,
			border_prefix = false,
			above = "▄",
			below = "▀",
			backgrounds = {
				"RenderMarkdownH1Bg",
				"RenderMarkdownH2Bg",
				"RenderMarkdownH3Bg",
				"RenderMarkdownH4Bg",
				"RenderMarkdownH5Bg",
				"RenderMarkdownH6Bg",
			},
			foregrounds = {
				"RenderMarkdownH1",
				"RenderMarkdownH2",
				"RenderMarkdownH3",
				"RenderMarkdownH4",
				"RenderMarkdownH5",
				"RenderMarkdownH6",
			},
			custom = {},
		},
		code = {
			enabled = true,
			render_modes = true,
			sign = true,
			conceal_delimiters = true,
			language = true,
			position = "left",
			language_icon = true,
			language_name = true,
			language_info = true,
			language_pad = 0,
			disable_background = false,
			width = "block",
			left_margin = 0,
			left_pad = 2,
			right_pad = 4,
			min_width = 0,
			border = "hide",
			language_border = "█",
			language_left = "",
			language_right = "",
			above = "▄",
			below = "▀",
			inline = true,
			inline_left = "",
			inline_right = "",
			inline_pad = 0,
			highlight = "RenderMarkdownCode",
			highlight_info = "RenderMarkdownCodeInfo",
			highlight_language = nil,
			highlight_border = "RenderMarkdownCodeBorder",
			highlight_fallback = "RenderMarkdownCodeFallback",
			highlight_inline = "RenderMarkdownCodeInline",
			style = "full",
		},
		dash = {
			enabled = true,
			render_modes = false,
			icon = "─",
			width = "full",
			left_margin = 0,
			highlight = "RenderMarkdownDash",
		},
		callout = {
			note = { raw = "[!NOTE]", rendered = "󰋽 Note", highlight = "RenderMarkdownInfo", category = "github" },
			tip = { raw = "[!TIP]", rendered = "󰌶 Tip", highlight = "RenderMarkdownSuccess", category = "github" },
			important = {
				raw = "[!IMPORTANT]",
				rendered = "󰅾 Important",
				highlight = "RenderMarkdownHint",
				category = "github",
			},
			warning = {
				raw = "[!WARNING]",
				rendered = "󰀪 Warning",
				highlight = "RenderMarkdownWarn",
				category = "github",
			},
			caution = {
				raw = "[!CAUTION]",
				rendered = "󰳦 Caution",
				highlight = "RenderMarkdownError",
				category = "github",
			},
			abstract = {
				raw = "[!ABSTRACT]",
				rendered = "󰨸 Abstract",
				highlight = "RenderMarkdownInfo",
				category = "obsidian",
			},
			summary = {
				raw = "[!SUMMARY]",
				rendered = "󰨸 Summary",
				highlight = "RenderMarkdownInfo",
				category = "obsidian",
			},
			tldr = { raw = "[!TLDR]", rendered = "󰨸 Tldr", highlight = "RenderMarkdownInfo", category = "obsidian" },
			info = { raw = "[!INFO]", rendered = "󰋽 Info", highlight = "RenderMarkdownInfo", category = "obsidian" },
			todo = { raw = "[!TODO]", rendered = "󰗡 Todo", highlight = "RenderMarkdownInfo", category = "obsidian" },
			hint = {
				raw = "[!HINT]",
				rendered = "󰌶 Hint",
				highlight = "RenderMarkdownSuccess",
				category = "obsidian",
			},
			success = {
				raw = "[!SUCCESS]",
				rendered = "󰄬 Success",
				highlight = "RenderMarkdownSuccess",
				category = "obsidian",
			},
			check = {
				raw = "[!CHECK]",
				rendered = "󰄬 Check",
				highlight = "RenderMarkdownSuccess",
				category = "obsidian",
			},
			done = {
				raw = "[!DONE]",
				rendered = "󰄬 Done",
				highlight = "RenderMarkdownSuccess",
				category = "obsidian",
			},
			question = {
				raw = "[!QUESTION]",
				rendered = "󰘥 Question",
				highlight = "RenderMarkdownWarn",
				category = "obsidian",
			},
			help = { raw = "[!HELP]", rendered = "󰘥 Help", highlight = "RenderMarkdownWarn", category = "obsidian" },
			faq = { raw = "[!FAQ]", rendered = "󰘥 Faq", highlight = "RenderMarkdownWarn", category = "obsidian" },
			attention = {
				raw = "[!ATTENTION]",
				rendered = "󰀪 Attention",
				highlight = "RenderMarkdownWarn",
				category = "obsidian",
			},
			failure = {
				raw = "[!FAILURE]",
				rendered = "󰅖 Failure",
				highlight = "RenderMarkdownError",
				category = "obsidian",
			},
			fail = { raw = "[!FAIL]", rendered = "󰅖 Fail", highlight = "RenderMarkdownError", category = "obsidian" },
			missing = {
				raw = "[!MISSING]",
				rendered = "󰅖 Missing",
				highlight = "RenderMarkdownError",
				category = "obsidian",
			},
			danger = {
				raw = "[!DANGER]",
				rendered = "󱐌 Danger",
				highlight = "RenderMarkdownError",
				category = "obsidian",
			},
			error = {
				raw = "[!ERROR]",
				rendered = "󱐌 Error",
				highlight = "RenderMarkdownError",
				category = "obsidian",
			},
			bug = { raw = "[!BUG]", rendered = "󰨰 Bug", highlight = "RenderMarkdownError", category = "obsidian" },
			example = {
				raw = "[!EXAMPLE]",
				rendered = "󰉹 Example",
				highlight = "RenderMarkdownHint",
				category = "obsidian",
			},
			quote = {
				raw = "[!QUOTE]",
				rendered = "󱆨 Quote",
				highlight = "RenderMarkdownQuote",
				category = "obsidian",
			},
			cite = { raw = "[!CITE]", rendered = "󱆨 Cite", highlight = "RenderMarkdownQuote", category = "obsidian" },
		},
		quote = { repeat_linebreak = true },
		paragraph = {
			enabled = true,
			render_modes = false,
			left_margin = 0,
			indent = 0,
			min_width = 0,
		},
	},
	config = function(_, opts)
		-- 先设置高亮
		vim.api.nvim_set_hl(0, "RenderMarkdownCode", { bg = "#2D3748" })
		-- 然后调用插件设置
		require("render-markdown").setup(opts)
	end,
}
